# import re
# from playwright.sync_api import Playwright, sync_playwright, expect


# def run(playwright: Playwright) -> None:
#     browser = playwright.chromium.launch(headless=False)
#     context = browser.new_context()
#     page = context.new_page()
#     page.goto("http://103.204.95.218:7050/")
#     page.get_by_role("textbox", name="Enter your email id").click()
#     page.get_by_role("textbox", name="Enter your email id").fill("sherpa.local.com")
#     page.locator(".flex.flex-col.gap-\\[2vh\\] > div:nth-child(2)").click()
#     page.get_by_role("textbox", name="Enter your password").fill("sherpa@123")
#     page.get_by_role("button").filter(has_text=re.compile(r"^$")).click()
#     page.get_by_role("button", name="LOGIN").click()
#     page.get_by_role("textbox", name="Enter your email id").click()
#     page.get_by_role("textbox", name="Enter your email id").press("ArrowLeft")
#     page.get_by_role("textbox", name="Enter your email id").press("ArrowLeft")
#     page.get_by_role("textbox", name="Enter your email id").press("ArrowLeft")
#     page.get_by_role("textbox", name="Enter your email id").press("ArrowLeft")
#     page.get_by_role("textbox", name="Enter your email id").press("ArrowLeft")
#     page.get_by_role("textbox", name="Enter your email id").press("ArrowLeft")
#     page.get_by_role("textbox", name="Enter your email id").press("ArrowLeft")
#     page.get_by_role("textbox", name="Enter your email id").press("ArrowLeft")
#     page.get_by_role("textbox", name="Enter your email id").press("ArrowLeft")
#     page.get_by_role("textbox", name="Enter your email id").fill("sherpa@local.com")
#     page.get_by_role("button", name="LOGIN").click()
#     page.locator("div").filter(has_text=re.compile(r"^Profile Dictionary$")).click()
#     page.get_by_role("button", name="Go to App").first.click()
#     page.locator(".absolute.right-\\[0\\.7vw\\] > .w-\\[1\\.5vw\\]").click()
#     page.locator(".w-\\[1\\.5vw\\]").first.click()
#     page.locator(".w-\\[2vw\\].h-\\[2vw\\].flex.items-center.justify-center.rounded-\\[0\\.5vw\\].bg-\\[linear-gradient\\(90deg\\,\\#0D405D_0\\%\\,\\#316D90_100\\%\\)\\].cursor-pointer").click()
#     page.get_by_role("button", name="Back").click()
#     page.get_by_role("button", name="Register Profile").click()
#     page.get_by_role("textbox", name="e.g. Profile A").click()
#     page.get_by_role("textbox", name="e.g. Profile A").press("CapsLock")
#     page.get_by_role("textbox", name="e.g. Profile A").fill("T")
#     page.get_by_role("textbox", name="e.g. Profile A").press("CapsLock")
#     page.get_by_role("textbox", name="e.g. Profile A").fill("Test")
#     page.get_by_role("textbox", name="Enter control class").click()
#     page.get_by_role("textbox", name="Enter control class").fill("burst")
#     page.get_by_role("textbox", name="Type here...").click()
#     page.get_by_role("textbox", name="Type here...").fill("12345678")
#     page.get_by_role("button", name="Propose options").click()
#     page.locator("div:nth-child(2) > .flex.items-center.gap-\\[0\\.6vw\\] > .w-\\[0\\.9vw\\]").click()
#     page.locator(".absolute.right-\\[1vw\\].z-50").click()
#     page.locator(".absolute.left-\\[1vw\\]").click()
#     page.get_by_role("button", name="Check Similarity").click()
#     page.locator("div").filter(has_text=re.compile(r"^burst$")).first.click()
#     page.locator("div").filter(has_text=re.compile(r"^Description:$")).first.click()
#     page.locator("div").filter(has_text=re.compile(r"^Check Similarity$")).click()
#     page.get_by_text("Sustained High-Power Plateaus").click()
#     page.get_by_role("button", name="Preview").click()
#     page.get_by_text("burstCreated with Highcharts").click()
#     page.get_by_role("button", name="Confirm").click()
#     page.get_by_role("button", name="Yes").click()
#     page.get_by_role("button", name="User Generated Profiles").click()
#     page.locator(".absolute.right-\\[0\\.7vw\\] > .w-\\[1\\.5vw\\]").click()
#     page.locator(".w-\\[1\\.5vw\\]").first.click()
#     page.locator("div:nth-child(5) > .w-full.h-full.rounded-\\[0\\.7vw\\] > .flex-1 > .w-full").click()
#     page.locator(".w-\\[2vw\\].h-\\[2vw\\].flex.items-center.justify-center.rounded-\\[0\\.5vw\\].bg-\\[linear-gradient\\(90deg\\,\\#0D405D_0\\%\\,\\#316D90_100\\%\\)\\].cursor-pointer").click()
#     page.get_by_text("User Generated GraphRecently").click()
#     page.get_by_role("heading", name="Description:").click()
#     page.get_by_role("button").first.click()
#     page.get_by_role("button", name="Go to App").nth(2).click()

#     # ---------------------
#     context.close()
#     browser.close()


# with sync_playwright() as playwright:
#     run(playwright)
